apiVersion: kafka.strimzi.io/v1alpha1
kind: Kafka
metadata:
  name: my-cluster
  labels:
    app: my-cluster
spec:
  kafka:
    replicas: 1
    listeners:
      plain: {}
    storage:
      type: ephemeral
    #storage:
    #  type: persistent-claim
    # size: 1Gi
    config:
      log.flush.interval.ms: 1000
      default.replication.factor: 1
      offsets.topic.replication.factor: 1
      transaction.state.log.min.isr: 1
      transaction.state.log.replication.factor: 1
  zookeeper:
    replicas: 1
    storage:
      type: ephemeral
    #storage:
    #type: persistent-claim
    #size: 1Gi
