apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaConnectS2I
metadata:
  name: my-connect-cluster
spec:
  replicas: 1
  readinessProbe:
    initialDelaySeconds: 60
    timeoutSeconds: 5
  livenessProbe:
    initialDelaySeconds: 60
    timeoutSeconds: 5
  #bootstrapServers: kafka-bootstrap:9092
  bootstrapServers: my-cluster-kafka-bootstrap:9092
  metrics:
    lowercaseOutputName: true
  config:
    default.replication.factor: 1
    config.storage.replication.factor: 1
    offset.storage.replication.factor: 1
    status.storage.replication.factor: 1
---
apiVersion: v1
kind: Service
metadata:
  name: src-connector     
spec:
  ports:
  - name: tcp
    port: 24224               
    protocol: TCP
    targetPort: 24224
  - name: udp
    port: 24424
    protocol: UDP
    targetPort: 24224
  selector:
    strimzi.io/cluster: my-connect-cluster
    strimzi.io/kind: KafkaConnectS2I
    strimzi.io/name: my-connect-cluster-connect
