apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaConnectS2I
metadata:
  name: my-connect-cluster
spec:
  replicas: 1
  readinessProbe:
    initialDelaySeconds: 60
    timeoutSeconds: 5
  livenessProbe:
    initialDelaySeconds: 60
    timeoutSeconds: 5
  #bootstrapServers: kafka-bootstrap:9092
  bootstrapServers: my-cluster-kafka-bootstrap:9092
  metrics:
    lowercaseOutputName: true
  config:
    default.replication.factor: 1
    config.storage.replication.factor: 1
    offset.storage.replication.factor: 1
    status.storage.replication.factor: 1
