apiVersion: v1
kind: Service
metadata:
  name: src-connector     
spec:
  ports:
  - name: tcp
    port: 24224               
    protocol: TCP
    targetPort: 24224
  - name: udp
    port: 24424
    protocol: UDP
    targetPort: 24224
  selector:
    strimzi.io/cluster: my-connect-cluster
    strimzi.io/kind: KafkaConnectS2I
    strimzi.io/name: my-connect-cluster-connect
